<ol>
    <?php foreach ($this->getItems() as $_item): ?>
    <?php $url = $this->urlEscape(($_item->isSelected()) ? $_item->getRemoveUrl() : $_item->getUrl()); ?>
        <li>
            <a href="<?php echo $url; ?>">
                <?php echo $_item->getLabel() ?>
                <?php if ($this->shouldDisplayProductCount()): ?>
                <?php endif; ?>
            </a>
        </li>
    <?php endforeach ?>
</ol>
